name: Test and publish
on:
  push:
    branches: [ develop ]
    paths:
      - '!README.md'
#      - '!*.yml'
#      - '!art/**'
#      - '!build.gradle'
#      - '!build.gradle.kts'

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint and tests
        run: |
          ./gradlew ktlint test
      - name: 'Publish Plugin Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'update-changelog-test-report'
          path: update-changelog/build/reports/tests/*