name: Test and publish
on:
  push:
    branches: [ develop ]
    paths:
      - '!README.md'
      - '!*.yml'
      - '!gradle.properties'
      - '!art/**'
      - '!build.gradle'
      - '!build.gradle.kts'

jobs:
  unit-tests:
    runs-on: macos-latest
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint and tests
        run: |
          ./gradlew ktlint test
      - name: 'bump-version-code Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'bump-version-code-test-report'
          path: bump-version-code/build/reports/tests/*
      - name: 'git-utils Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'git-utils-test-report'
          path: git-utils/build/reports/tests/*
      - name: 'replace-in-file Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'replace-in-file-test-report'
          path: replace-in-file/build/reports/tests/*
      - name: 'update-changelog Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'update-changelog-test-report'
          path: update-changelog/build/reports/tests/*
